# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sharedobjects_num_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedobjects',
            name='date_added',
            field=models.DateField(default=datetime.date(2017, 7, 8)),
        ),
    ]
