# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sharedobjects_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedobjects',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 7, 8, 12, 33, 42, 757290, tzinfo=utc)),
        ),
    ]
