# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170708_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedobjects',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sharedobjects',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 7, 8, 14, 30, 23, 571423, tzinfo=utc)),
        ),
    ]
