# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-09 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170709_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='settings.MEDIA_ROOT/media/profile-icon.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sharedobjects',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 7, 9, 11, 36, 52, 34951, tzinfo=utc)),
        ),
    ]
