# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-09 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20170709_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='{% static "website/images/profile-icon.png" %}', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sharedobjects',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 7, 9, 11, 40, 17, 624202, tzinfo=utc)),
        ),
    ]
