# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 20:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170709_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedobjects',
            old_name='likes',
            new_name='views',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='profile-icon.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sharedobjects',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 7, 18, 20, 3, 54, 947192, tzinfo=utc)),
        ),
    ]
