# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 15:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20170718_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionobjects',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='auction_object',
        ),
        migrations.AlterField(
            model_name='sharedobjects',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 7, 21, 15, 43, 9, 661524, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='AuctionObjects',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
