# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20170721_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='friend_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='request',
            name='friend_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='sharedobjects',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 7, 21, 18, 34, 53, 247490, tzinfo=utc)),
        ),
    ]
