# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20170721_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='last_conversation',
            field=models.DateField(default=datetime.date(1997, 3, 30)),
        ),
        migrations.AlterField(
            model_name='sharedobjects',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 7, 22, 8, 16, 0, 475367, tzinfo=utc)),
        ),
    ]
