# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20170722_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedobjects',
            name='date_added',
            field=models.DateField(default=datetime.date(1997, 3, 30)),
        ),
    ]
