# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-22 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20170722_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conv_time',
            field=models.DateTimeField(default=datetime.datetime(1997, 3, 30, 0, 0)),
        ),
    ]
